# Generated by Django 4.2.2 on 2023-06-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedObjectCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'AbandonedObjectCategory',
                'verbose_name_plural': 'AbandonedObjectCategories',
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Coordinates',
                'verbose_name_plural': 'Coordinates',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(default=None, max_length=100, null=True)),
                ('street_number', models.CharField(default=None, max_length=4, null=True)),
                ('zipcode', models.CharField(default=None, max_length=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AbandonedObjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abandoned.address')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abandoned.coordinates')),
            ],
            options={
                'verbose_name': 'AbandonedObjectLocation',
                'verbose_name_plural': 'AbandonedObjectLocations',
            },
        ),
        migrations.CreateModel(
            name='AbandonedObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('hidden', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('d', 'dangerous'), ('b', 'bad'), ('a', 'average'), ('g', 'good'), ('n', 'novelty')], default='a', max_length=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abandoned.abandonedobjectcategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abandoned.abandonedobjectlocation')),
            ],
            options={
                'verbose_name': 'AbandonedObject',
                'verbose_name_plural': 'AbandonedObjects',
            },
        ),
    ]
